
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "backend"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3", default-features = false, features = ["napi4", "async", "tokio_rt"] }
napi-derive = "3.0.0"
serde_json = { version = "1", features = ["preserve_order"] }
sqlitex = "0.4.3"
tokio = { version = "1", features = ["rt"] }

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
