import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

// Import the Rust Native Module we created.
// Because we marked this as 'external' in esbuild.js, VS Code will safely
// require() the native binary at runtime without bundling errors.
import { Database } from '../backend';

export function activate(context: vscode.ExtensionContext) {
  context.subscriptions.push(
    vscode.commands.registerCommand('monaco-hello.open', () => {

      const webviewDir = vscode.Uri.file(path.join(context.extensionPath, 'dist', 'webview'));

      const panel = vscode.window.createWebviewPanel(
        'monacoEditor',
        'Svelte Monaco',
        vscode.ViewColumn.One,
        {
          enableScripts: true,
          retainContextWhenHidden: true,
          localResourceRoots: [webviewDir]
        }
      );

      // Read the HTML file generated by Vite
      const htmlPath = path.join(webviewDir.fsPath, 'index.html');
      let html = fs.readFileSync(htmlPath, 'utf8');

      // Inject the Webview URI base path into the <head> so CSS and JS load correctly
      const webviewUri = panel.webview.asWebviewUri(webviewDir);

      // We add the base href so all the asset paths resolve correctly inside VS Code's environment
      html = html.replace(
        '<head>',
        `<head>\n    <base href="${webviewUri}/">`
      );

      panel.webview.html = html;

      try {
        // 1. Initialize the Rust sqlitex Database (using in-memory for testing)
        const db = new Database(":memory:");

        // 2. Setup some dummy data so you can immediately test queries in Monaco
        db.query("CREATE TABLE users (id INTEGER PRIMARY KEY, username TEXT, email TEXT);");
        db.query("INSERT INTO users (username, email) VALUES ('naresh', 'naresh@example.com');");
        db.query("INSERT INTO users (username, email) VALUES ('alice', 'alice@example.com');");

        // 3. Listen for messages coming from the Svelte webview
        panel.webview.onDidReceiveMessage(message => {

          if (message.command === 'runSql') {
            try {
              // Pass the SQL text to the Rust backend
              const jsonResult = db.query(message.text);

              // Parse the stringified JSON array coming from Rust
              const data = JSON.parse(jsonResult);

              // Send the parsed rows back to the Svelte Webview
              panel.webview.postMessage({ command: 'sqlResult', data });

            } catch (err: any) {
              // Catch syntax errors or DB errors and send them back to the UI
              panel.webview.postMessage({ command: 'sqlError', error: err.message });
            }
          }

        });

      } catch (err: any) {
        vscode.window.showErrorMessage(`Failed to initialize Database: ${err.message}`);
      }

    })
  );
}

export function deactivate() {}