import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

export function activate(context: vscode.ExtensionContext) {
  context.subscriptions.push(
    vscode.commands.registerCommand('monaco-hello.open', () => {

      const webviewDir = vscode.Uri.file(path.join(context.extensionPath, 'dist', 'webview'));

      const panel = vscode.window.createWebviewPanel(
        'monacoEditor',
        'Svelte Monaco',
        vscode.ViewColumn.One,
        {
          enableScripts: true,
          retainContextWhenHidden: true,
          localResourceRoots: [webviewDir]
        }
      );

      // Read the HTML file generated by Vite
      const htmlPath = path.join(webviewDir.fsPath, 'index.html');
      let html = fs.readFileSync(htmlPath, 'utf8');

      // Inject the Webview URI base path into the <head> so CSS and JS load correctly
      const webviewUri = panel.webview.asWebviewUri(webviewDir);

      // We add the base href so all the asset paths resolve correctly inside VS Code's environment
      html = html.replace(
        '<head>',
        `<head>\n    <base href="${webviewUri}/">`
      );

      panel.webview.html = html;
    })
  );
}

export function deactivate() {}